language: node_js
cache:
  directories:
  - node_modules
install:
  - yarn install
  - npm install -g serverless serverless-offline
deploy:
  - provider: script
    script: yarn deploy
    on:
      branch: master